// default package
// Generated Dec 4, 2016 1:05:32 AM by Hibernate Tools 4.3.1.Final

package model;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblaccount generated by hbm2java
 */
public class Tblaccount  implements java.io.Serializable {


     private int userId;
     private String name;
     private String email;
     private Set tblcomments = new HashSet(0);

    public Tblaccount() {
    }

	
    public Tblaccount(int userId) {
        this.userId = userId;
    }
    public Tblaccount(int userId, String name, String email, Set tblcomments) {
       this.userId = userId;
       this.name = name;
       this.email = email;
       this.tblcomments = tblcomments;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTblcomments() {
        return this.tblcomments;
    }
    
    public void setTblcomments(Set tblcomments) {
        this.tblcomments = tblcomments;
    }




}


