// default package
// Generated Dec 4, 2016 1:05:32 AM by Hibernate Tools 4.3.1.Final


package model;
/**
 * Tblcomment generated by hbm2java
 */
public class Tblcomment  implements java.io.Serializable {


     private int commentId;
     private Tblaccount tblaccount;
     private Tblnews tblnews;
     private String commentContent;

    public Tblcomment() {
    }

	
    public Tblcomment(int commentId) {
        this.commentId = commentId;
    }
    public Tblcomment(int commentId, Tblaccount tblaccount, Tblnews tblnews, String commentContent) {
       this.commentId = commentId;
       this.tblaccount = tblaccount;
       this.tblnews = tblnews;
       this.commentContent = commentContent;
    }
   
    public int getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }
    public Tblaccount getTblaccount() {
        return this.tblaccount;
    }
    
    public void setTblaccount(Tblaccount tblaccount) {
        this.tblaccount = tblaccount;
    }
    public Tblnews getTblnews() {
        return this.tblnews;
    }
    
    public void setTblnews(Tblnews tblnews) {
        this.tblnews = tblnews;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }




}


